title: Digital Apprenticeship Service - manuals
email: gregdbarnes@gmail.com
description: >-
  Prototype of manuals for use by ESFA DAS
baseurl: '/employer-funding-rules'
url: ''

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
